# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 456)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 721, 411))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.PlayButton = QtWidgets.QPushButton(self.widget)
        self.PlayButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/1/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlayButton.setIcon(icon)
        self.PlayButton.setObjectName("PlayButton")
        self.gridLayout.addWidget(self.PlayButton, 1, 0, 1, 1)
        self.StopButton = QtWidgets.QPushButton(self.widget)
        self.StopButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/1/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StopButton.setIcon(icon1)
        self.StopButton.setIconSize(QtCore.QSize(20, 20))
        self.StopButton.setObjectName("StopButton")
        self.gridLayout.addWidget(self.StopButton, 1, 2, 1, 1)
        self.VolumeButton = QtWidgets.QPushButton(self.widget)
        self.VolumeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/1/Volume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VolumeButton.setIcon(icon2)
        self.VolumeButton.setCheckable(True)
        self.VolumeButton.setObjectName("VolumeButton")
        self.gridLayout.addWidget(self.VolumeButton, 1, 4, 1, 1)
        self.PauseButton = QtWidgets.QPushButton(self.widget)
        self.PauseButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/1/Pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PauseButton.setIcon(icon3)
        self.PauseButton.setObjectName("PauseButton")
        self.gridLayout.addWidget(self.PauseButton, 1, 1, 1, 1)
        self.VideoWidget = QVideoWidget(self.widget)
        self.VideoWidget.setObjectName("VideoWidget")
        self.gridLayout.addWidget(self.VideoWidget, 0, 0, 1, 8)
        self.TimeSlider = QtWidgets.QSlider(self.widget)
        self.TimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TimeSlider.setObjectName("TimeSlider")
        self.gridLayout.addWidget(self.TimeSlider, 1, 3, 1, 1)
        self.FullscreenButton = QtWidgets.QPushButton(self.widget)
        self.FullscreenButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/1/Fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FullscreenButton.setIcon(icon4)
        self.FullscreenButton.setCheckable(True)
        self.FullscreenButton.setObjectName("FullscreenButton")
        self.gridLayout.addWidget(self.FullscreenButton, 1, 7, 1, 1)
        self.MuteButton = QtWidgets.QPushButton(self.widget)
        self.MuteButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/1/Mute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MuteButton.setIcon(icon5)
        self.MuteButton.setCheckable(True)
        self.MuteButton.setObjectName("MuteButton")
        self.gridLayout.addWidget(self.MuteButton, 1, 6, 1, 1)
        self.VolumeSlider = QtWidgets.QSlider(self.widget)
        self.VolumeSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.VolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.VolumeSlider.setObjectName("VolumeSlider")
        self.gridLayout.addWidget(self.VolumeSlider, 1, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.OpenAction = QtWidgets.QAction(MainWindow)
        self.OpenAction.setObjectName("OpenAction")
        self.menu.addAction(self.OpenAction)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "lliriq\'s VideoPlayer"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.OpenAction.setText(_translate("MainWindow", "Открыть"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
import Images.img
